### ISSUE TITLE
This havent updated in a while.

### ISSUE THREAD

**Issue by Bradisverycool** [mopenstein/raspberry-pi-movie-theater-projector#1]
Um we may need to update this. This haven't been updated in 3 whole years.

**Comment by mopenstein** [comment]
It's done.

**Comment by Bradisverycool** [comment]
ok but you may need to switch to mpv because of the discontinue of omx player

**Comment by mopenstein** [comment]
> ok but you may need to switch to mpv because of the discontinue of omx player

I appreciate your sentiment but I'm just not updating it. Feel free to fork. It works perfectly as is.
